services:
  app: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: "${SOURCE}"
        target: /backend/src/static/data
    ports:
      - 5000:5000